apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: image-operator
    app.kubernetes.io/managed-by: kustomize
  name: webhook-service
  namespace: image-operator-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: image-operator
