image:
  repository: "tchoupinax/skopeo-operator"
  version: "v1.7.2"
  imagePullPolicy: "IfNotPresent"
  pullSecrets: []

affinity: {}
tolerations: []

config:
  source:
    disabledTlsCheck: false
  destination:
    disabledTlsCheck: false

  credentials:
    createSecret: true
    destinationPassword: ""
    destinationUsername: ""
    secretName: "skopeo-operator"
    sourcePassword: ""
    sourceUsername: ""
  pullJobNamespace: "skopeo-operator"
  skopeo:
    image: "quay.io/containers/skopeo"
    imageAwsIrsa: false
    version: "v1.16.1"
  buildah:
    dangerUsePrivilegedContainers: false
    image: "quay.io/containers/buildah"
    imageAwsIrsa: false
    version: "v1.37.3"
    jobNamespace: "skopeo-operator"

monitoring:
  podMonitor:
    enabled: false
    labels: {}
    podMetricsEndpoints:
    - path: "/metrics"
      port: "metrics"
