# permissions for end users to view imagebuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-operator
    app.kubernetes.io/managed-by: kustomize
  name: buildah.io-imagebuilder-viewer-role
rules:
- apiGroups:
  - buildah.io
  resources:
  - imagebuilders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - buildah.io
  resources:
  - imagebuilders/status
  verbs:
  - get
