{{- if and .Values.config.ui.enabled .Values.config.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-operator-ui
  annotations:
    {{- toYaml .Values.config.ui.ingress.annotations | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: image-operator-ui
            port:
              number: 3000
        pathType: "{{ .Values.config.ui.ingress.pathType }}"
        path: "/{{ .Values.config.ui.ingress.path }}"
    {{ if .Values.config.ui.ingress.host }}
    host: {{ .Values.config.ui.ingress.host }}
    {{ end }}
{{- end }}
