{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: image-operator
  labels:
    kubernetes.io/name: image-operator
    {{- if .Values.monitoring.podMonitor.labels }}
    {{- toYaml .Values.monitoring.podMonitor.labels | nindent 4 }}
    {{- end }}

spec:
  podMetricsEndpoints:
  {{- if .Values.monitoring.podMonitor.podMetricsEndpoints }}
{{ toYaml .Values.monitoring.podMonitor.podMetricsEndpoints | indent 2 }}
  {{ else }}
    - path: /metrics
      port: 8080
  {{ end }}

  selector:
    matchLabels:
      kubernetes.io/name: image-operator
{{- end }}
