{{- if .Values.config.credentials.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.config.credentials.secretName }}"

type: Opaque
stringData:
  credentialsDestinationUsername: "{{ .Values.config.credentials.destinationUsername }}"
  credentialsDestinationPassword: "{{ .Values.config.credentials.destinationPassword }}"
  credentialsSourceUsername: "{{ .Values.config.credentials.sourceUsername }}"
  credentialsSourcePassword: "{{ .Values.config.credentials.sourcePassword }}"
{{- end }}
