{{- if and .Values.config.ui.enabled .Values.config.ui.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: image-operator-ui
  annotations:
    {{- toYaml .Values.config.ui.ingress.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: web  
    port: 3000
  selector:
    kubernetes.io/name: image-operator-ui
{{- end }}
