apiVersion: buildah.io/v1alpha1
kind: ImageBuilder
metadata:
  labels:
    app.kubernetes.io/name: skopeo-operator
    app.kubernetes.io/managed-by: kustomize
  name: imagebuilder-sample
spec:
# TODO(user): Add fields here
