apiVersion: tchoupinax.dev/v1beta
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: image-operator
    app.kubernetes.io/managed-by: kustomize
  name: image-sample
spec: # TODO(user): Add fields here
