apiVersion: skopeo.io/v1alpha1
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: skopeo-operator
    app.kubernetes.io/managed-by: kustomize
  name: image-sample
spec:
  # TODO(user): Add fields here
