apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skopeo-operator

rules:
  - apiGroups: ["skopeo.io"]
    resources: ["images"]
    verbs: ["get", "list", "watch", "update"]

  - apiGroups: ["skopeo.io"]
    resources: ["images/status"]
    verbs: ["update"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create"]

  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
