apiVersion: apps/v1
kind: Deployment
metadata:
  name: skopeo-operator

spec:
  replicas: 1
  selector:
    matchLabels:
      kubernetes.io/name: skopeo-operator

  template:
    metadata:
      labels:
        kubernetes.io/name: skopeo-operator

    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{.Values.image.version}}"
        imagePullPolicy: "{{.Values.image.imagePullPolicy}}"
        name: skopeo-operator
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 20Mi
        env:
          - name: "CREDS_DESTINATION_USERNAME"
            value: "{{ .Values.config.credentials.destinationUsername }}"
          - name: "CREDS_DESTINATION_PASSWORD"
            value: "{{ .Values.config.credentials.destinationPassword }}"
          - name: "CREDS_SOURCE_USERNAME"
            value: "{{ .Values.config.credentials.sourceUsername }}"
          - name: "CREDS_SOURCE_PASSWORD"
            value: "{{ .Values.config.credentials.sourcePassword }}"
          - name: "PULL_JOB_NAMESPACE"
            value: "{{ .Values.config.pullJobNamespace }}"
          - name: "SKOPEO_IMAGE"
            value: "{{ .Values.config.skopeo.image }}"
          - name: "SKOPEO_VERSION"
            value: "{{ .Values.config.skopeo.version }}"
