apiVersion: v1
kind: Secret
metadata:
  name: skopeo-operator

type: Opaque
stringData:
  credentialsDestinationUsername: "{{ .Values.config.credentials.destinationUsername }}"
  credentialsDestinationPassword: "{{ .Values.config.credentials.destinationPassword }}"
  credentialsSourceUsername: "{{ .Values.config.credentials.sourceUsername }}"
  credentialsSourcePassword: "{{ .Values.config.credentials.sourcePassword }}"
