FROM node:22-alpine AS builder

COPY . .

RUN yarn && yarn build

###

FROM node:22-alpine

LABEL buildAt=2024-12-10

WORKDIR /app
USER 1001

COPY --from=builder .output /app/.output
COPY --from=builder package.json /app/package.json

CMD HOST=0.0.0.0 PORT=3000 node /app/.output/server/index.mjs
