image:
  repository: "tchoupinax/image-operator"
  version: "v2.11.2"
  imagePullPolicy: "IfNotPresent"
  pullSecrets: []

affinity: {}
tolerations: []
resources:
  memory:
    request: 100Mi
    limit: 300Mi

config:
  source:
    disabledTlsCheck: false
  destination:
    disabledTlsCheck: false
    defaultRegistry: ""
    defaultAwsIrsaUsage: false

  api:
    aws:
      pageMax: 4
      itemsByPage: 1000

  credentials:
    createSecret: true
    destinationPassword: ""
    destinationUsername: ""
    secretName: "image-operator"
    sourcePassword: ""
    sourceUsername: ""

  features:
    dockerHubRateLimit:
      enabled: false
      frequencySecond: 60
    copyOnTheFly:
      enabled: false
      namespacesAllowed:
      - "*"

  pullJobNamespace: "image-operator"
  skopeo:
    image: "quay.io/containers/skopeo"
    imageAwsIrsa: false
    version: "v1.16.1"
  buildah:
    dangerUsePrivilegedContainers: false
    image: "quay.io/containers/buildah"
    imageAwsIrsa: false
    version: "v1.37.5"
    jobNamespace: "image-operator"

  ui:
    enabled: false
    affinity: {}
    tolerations: []
    image:
      repository: "tchoupinax/image-operator-ui"
      version: "v2.11.2"
      imagePullPolicy: "IfNotPresent"
    apiUrl: "http://image-operator.image-operator.svc:9090/graphql"
    ingress:
      enabled: false
      annotations: {}
      path: ""
      pathType: "Prefix"
      host: ""

monitoring:
  podMonitor:
    enabled: false
    labels: {}
    podMetricsEndpoints:
    - path: "/metrics"
      port: "metrics"
