image:
  repository: "tchoupinax/image-operator"
  version: "v2.3.1"
  imagePullPolicy: "IfNotPresent"
  pullSecrets: []

affinity: {}
tolerations: []

config:
  source:
    disabledTlsCheck: false
  destination:
    disabledTlsCheck: false

  credentials:
    createSecret: true
    destinationPassword: ""
    destinationUsername: ""
    secretName: "image-operator"
    sourcePassword: ""
    sourceUsername: ""
  pullJobNamespace: "image-operator"
  skopeo:
    image: "quay.io/containers/skopeo"
    imageAwsIrsa: false
    version: "v1.16.1"
  buildah:
    dangerUsePrivilegedContainers: false
    image: "quay.io/containers/buildah"
    imageAwsIrsa: false
    version: "v1.38.0"
    jobNamespace: "image-operator"

  ui:
    enabled: false
    affinity: {}
    tolerations: []
    image:
      repository: "tchoupinax/image-operator-ui"
      version: "v2.3.0"
      imagePullPolicy: "IfNotPresent"
    apiUrl: "http://image-operator.image-operator.svc:9090/graphql"
    ingress:
      enabled: false
      annotations: {}
      path: ""
      pathType: "Prefix"
      host: ""

monitoring:
  podMonitor:
    enabled: false
    labels: {}
    podMetricsEndpoints:
    - path: "/metrics"
      port: "metrics"
