name: Build image operator UI next

on: workflow_dispatch

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'ui/.nvmrc'
    - name: Install dependencies
      run: yarn
    - name: Build Nuxt.js
      run: yarn build

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:ui"
        platforms: linux/amd64,linux/arm64
        push: true
        tags: tchoupinax/image-operator-ui:next
