name: release

on:
  push:
    branches:
      - master
  release:
    types: [published, created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts
